# -*- restclient -*-

:host = http://localhost/

:email = "sample@example.org"
:password = "Correct horse battery staple"
:token = placeholder_api_token

#
# Login API endpoint
#
POST :host/api/v1/login
Content-Type: application/json
Accept: application/json

{
    "email": :email,
    "password": :password
}

#
# Feeds related endpoints
#
GET :host/api/v1/feeds?token=:token
Content-Type: application/json
Accept: application/json

#
# Specific Feed related endpoints
#
GET :host/api/v1/feeds/1?token=:token
Content-Type: application/json
Accept: application/json
