# -*- restclient -*-

:host = http://localhost

:email = "sample@example.org"
:password = "Correct horse battery staple"
:token = placeholder_api_token

#
# Login API endpoint
#
POST :host/api/v1/login
Content-Type: application/json
Accept: application/json

{
    "email": :email,
    "password": :password
}

#
# Logout API endpoint
#
GET :host/api/v1/logout?token=:token
Accept: application/json

#
# Feeds related endpoints
#
GET :host/api/v1/feeds?token=:token
Accept: application/json

#
# Specific Feed related endpoints
#
GET :host/api/v1/feeds/1?token=:token
Accept: application/json

#
# Subscribe to new feed
#
POST :host/api/v1/feeds?token=:token
Content-Type: application/json
Accept: application/json

{
  "name": "example",
  "website_uri": "http://example.org",
  "feed_uri": "http://example.org/rss.xml",
  "update_interval": "5"
}

#
# Update an existing feed
#
PUT :host/api/v1/feeds/1?token=:token
Content-Type: application/json
Accept: application/json

{
  "name": "example2",
  "website_uri": "http://example.org",
  "feed_uri": "http://example.org/rss.xml",
  "update_interval": "5"
}

#
# Delete an existing feed
#
DELETE :host/api/v1/feeds/1?token=:token
Accept: application/json

#
# Get articles for a specific feed
#
GET :host/api/v1/feeds/1/articles?token=:token
Accept: application/json

#
# Get articles for a specific feed
#
GET :host/api/v1/articles/05899f5a23e3e7a87605db370d0eb9dc?token=:token
Accept: application/json

#
# Set starred / read for specific article
#
PUT :host/api/v1/articles/05899f5a23e3e7a87605db370d0eb9dc?token=:token
Content-Type: application/json
Accept: application/json

{
  "is_read": true,
  "is_starred": false
}
