# -*- restclient -*-

:host = http://localhost/

:email = "sample@example.org"
:password = "Correct horse battery staple"

#
# Login API endpoint
#
POST :host/api/v1/login
Content-Type: application/json
Accept: application/json

{
    "email": :email,
    "password": :password
}
