* 0bRSS - Simple RSS Reader

0bRSS is a Simple RSS-Reader.

** Requirements
 - PHP 5.4 or greater.
 - PostgreSQL or MySQL (InnoDB required).
 - Webserver that rewrites the URI's [[https://github.com/slimphp/Slim#setup-your-web-server][like this]].

** Installation
 - Clone the git-repo.
 - Install the composer dependencies (=php composer.phar install --no-dev=).
 - Write the config-file.
 - Run the migrations (=php vendor/bin/phinx migrate -c config.php=).
 - Create user (=php bin/create-user=).

** Updating feeds
Run the updater (=php bin/update-feeds=) every 5 minutes or something. Should
be easy with =systemd-timer= or =cron=. More info will come.

** Writing the config
Start by copying the =config.sample.php= to =config.php= and then change your
values to match your database configruation.

*** bcrypt settings
You may also set =bcrypt-password-cost= which will be used by the password
hashing. Bigger number -> Slower but better hashing.

There is a script provided (=php vendor/bin/cost-check=) which will benchmark
a cost for you which takes 0.2s to hash a password with. On my 5 year old
laptop, it suggests 11. So most people should be able to go higher than that.
As of writing, PHP defaults to 10.

The login also supports rehashing, so if you change your =bcrypt-password-cost=,
it will update the hash in the database on next login for the user logging in to
match the new cost set in the config.
