* 0bRSS - Simple RSS Reader

0bRSS is a Simple RSS-Reader.


** Requirements
 - PHP 5.4 or greater.
 - PostgreSQL or MySQL (InnoDB required).
 - Webserver that rewrites the URI's [[https://github.com/slimphp/Slim#setup-your-web-server][like this]].


** Installation
 - Clone the git-repo.
 - Install the composer dependencies (=php composer.phar install --no-dev=).
 - Write the config-file.
 - Run the migrations (=php vendor/bin/phinx migrate -c config.php=).
 - Create user (=php bin/create-user=).


** Writing the config
Start by copying the =config.sample.php= to =config.php= and then change your
values to match your database configruation.

*** bcrypt settings
You may also set =bcrypt-password-cost= which will be used by the password
hashing. Bigger number -> Slower but better hashing.

There is a script provided (=php vendor/bin/cost-check=) which will benchmark
a cost for you which takes 0.2s to hash a password with. On my 5 year old
laptop, it suggests 11. So most people should be able to go higher than that.
As of writing, PHP defaults to 10.

The login also supports rehashing, so if you change your =bcrypt-password-cost=,
it will update the hash in the database on next login for the user logging in to
match the new cost set in the config.


** Updating feeds
Run the updater (=php bin/update-feeds=) every 5 minutes or something. Should
be easy with =systemd-timer= or =cron=. More info will come.

*** systemd way:
=systemd= requires you to add to files to your system, one service file and one
timer file. The timer will be the the job responsible for running the service.

**** systemd service file
#+BEGIN_SRC ini
# Filename: /etc/systemd/system/0bRSS-updater.service
[Unit]
Description=0bRSS updater
After=syslog.target network.target postgresql-9.4.service

[Service]
User=nginx
Group=nginx
Type=simple
ExecStart=/usr/bin/php bin/update-feeds
WorkingDirectory=/srv/http/0bRSS
PrivateTmp=true
InaccessibleDirectories=/home /root /boot /opt /mnt /media

[Install]
WantedBy=multi-user.target
#+END_SRC

**** systemd timer file
#+BEGIN_SRC ini
# Filename: /etc/systemd/system/0bRSS-updater.timer
[Unit]
Description=Run 0bRSS updater every 5 minutes

[Timer]
OnBootSec=1min
OnUnitActiveSec=5min

[Install]
WantedBy=timers.target
#+END_SRC

**** Activate the updater
To activate the timer, you need to do =systemctl enable 0bRSS-updater.timer= and
possibly =systemctl start 0bRSS-updater.timer=.

**** Monitor the updater
You can check status on the timer with this command
 =systemctl status 0bRSS-updater.timer=, you can also check on the service to
get some useful information like this  =systemctl status 0bRSS-updater=.
